MODEL:
  TYPE: keypoint_rcnn
  CONV_BODY: ResNet3D.add_ResNet18_conv4_body
  ROI_HEAD: ResNet3D.add_ResNet18_roi_conv5_head
  NUM_CLASSES: 2
  FASTER_RCNN: True
  KEYPOINTS_ON: True
  VIDEO_ON: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001 # 0.00004 # 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001 # 0.002
  GAMMA: 0.1
  MAX_ITER: 13000 # 90000
  STEPS: [0, 10000, 12000] # [0, 60000, 80000]
FAST_RCNN:
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
KRCNN:
  ROI_KEYPOINTS_HEAD: keypoint_rcnn_heads.add_roi_pose_head_v1convX_3d
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox
  NO_3D_DECONV_TIME_TO_CH: True
VIDEO:
  NUM_FRAMES: 3
  TIME_INTERVAL: 1
  WEIGHTS_INFLATE_MODE: center-only
  TIME_KERNEL_DIM: 3
  BODY_HEAD_LINK: ''  # Needs 3D head
  PREDICT_RPN_BOX_VIS: False
TRAIN:
  WEIGHTS: /mnt/vol/gfsai-east/ai-group/users/rgirdhar/StandardModels/ImageNet/ResNet18_weights.pkl
  # DATASET: keypoints_coco_2014_train:keypoints_coco_2014_valminusminival
  DATASET: posetrack_v1.0_train
  SCALES: (128, 196, 256)
  MAX_SIZE: 333
  # SCALES: (600,)
  # MAX_SIZE: 1000
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  # DATASET: keypoints_coco_2014_minival
  DATASET: posetrack_v1.0_val
  SCALES: (256,)
  MAX_SIZE: 333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  COMPETITION_MODE: False
TRACKING:
  CONF_FILTER_INITIAL_DETS: 0.95
  DISTANCE_METRICS: ('bbox-overlap', 'cnn-cosdist')
  DISTANCE_METRIC_WTS: (1.0, 0.0)
  BIPARTITE_MATCHING_ALGO: 'hungarian'
EVAL:
  EVAL_MPII_KPT_THRESHOLD: 1.95
USE_NCCL: False
OUTPUT_DIR: .
